### ISSUE TITLE
Failing on non-200 status codes

### ISSUE THREAD

**Issue by lainga9** [spatie/laravel-export#38]
Is there a way to skip paths which return a non-200 status code rather than aborting entirely?

**Comment by sebastiandedeyne** [comment]
When would you want this? Personally I'd rather have the entire process fail, but if there's a good use case to do otherwise I'm open for a PR.

**Comment by Gummibeer** [comment]
I would vote to ignore `3xx` status codes - possibly reporting them as
> ignored `/old/url` because it redirects to `/new/url`

This way the user has a great report and can create redirects in the netlify.toml or any other tool.
This is primary a problem if used with the crawler functionality.
Let's say I have a paginated list and want to redirect the `/blog/p:1` to `/blog` to keep URLs canonical.
Adding the logic is super easy - but as soon as the first page is anywhere linked it will fail the export because it found a link which redirects instead of returning real content.
